// <auto-generated />
using System;
using Maurice.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Maurice.Data.Migrations
{
    [DbContext(typeof(MauriceDbContext))]
    [Migration("20250102035514_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Maurice.Data.DBModels.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Base")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importe")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreEmisor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RfcEmisor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RfcReceptor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tasa")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalImpuesto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Maurice.Data.DBModels.LimitesIsrSat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CuotaFija")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LimiteInferior")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LimiteSuperior")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Periodo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcentajeSobreLimiteInferior")
                        .HasColumnType("TEXT");

                    b.Property<int>("RegimenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RegimenId");

                    b.ToTable("LimitesIsrSat");
                });

            modelBuilder.Entity("Maurice.Data.DBModels.RegimenFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RegimenFiscal");
                });

            modelBuilder.Entity("Maurice.Data.DBModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Maurice.Data.DBModels.LimitesIsrSat", b =>
                {
                    b.HasOne("Maurice.Data.DBModels.RegimenFiscal", "Regimen")
                        .WithMany()
                        .HasForeignKey("RegimenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regimen");
                });

            modelBuilder.Entity("Maurice.Data.DBModels.RegimenFiscal", b =>
                {
                    b.HasOne("Maurice.Data.DBModels.User", null)
                        .WithMany("RegimenFiscal")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Maurice.Data.DBModels.User", b =>
                {
                    b.Navigation("RegimenFiscal");
                });
#pragma warning restore 612, 618
        }
    }
}
